---
  colors:
    bg: '#fff'
    fg: '#fff'       # Color of the text if displayed
  manager:
    steps: 0         # Number of steps between 2 sentences / sequences
    transition: 1000 # Time transition between all steps
    toLoop: True     # Loop over received information
    last_messages : -1 # Nb of previsous sessions messages to show. If -1 show all.
  display:
    colors: False    # Weither to show the colors
    text: False      # Show text on top of colors
  print:         
    text: True       # Print text in the command line
    mode: "debug"    # Print text or debug info. Can either be demo or debug
  models:
    version: 0       # Sentiment analysis model version. Can either be 0 or 1
    threshold: 0.66  # Threshold to consider a label neutral
  midi:
    nb_port: 1   # Number of Midi output port on which to send midi data
    label_cc_nb: 10  # Control Change number for label value
    score_int_cc_nb: 11 #Control Change number for integer part of score (between 0 and 100)
    score_float_cc_nb: 12 #Control Change number for floating part of score (between 0 and 100)
  osc:
    ip: [ '127.0.0.1' ] # ip adresses of receiving hosts
    port: [ 5000 ]   # udp port on which the host will listen to