---
  colors:
    bg: ['#ff5722', '#e64e1f', '#cc461b', '#b33d18', '#993414', '#802c11', '#66230e', '#4d1a0a', '#331107', '#190903']
    fg: '#fff'
  display:
    steps: 1000
    transition: 10
    showText: False
    printText: False
    toLoop: False
  models:
    version: 0