---
  colors:
    positive: 
      bg: "#45be25" # green
      fg: "#fff"    # white
    negative: 
      bg: "#c42510" # red
      fg: "#fff"    # white
    neutral:
      bg: "#edd626" # yellow
      fg: "#fff"    # white
  time:
    text: 1000
    transition: 1000
  models:
    version: 0
